### ISSUE TITLE
설치 방법 read.md 

### ISSUE THREAD

**Issue by qwopqwop200** [toriato/stable-diffusion-webui-wd14-tagger#1]
git clone으로 설치한는 것보다 webui Extension -> install from URL로 설명 하는게 더 나은 방법인것같음
![image](https://user-images.githubusercontent.com/64115820/202451399-527b1891-8aa9-4faa-bf7e-1c2c9cbe7fa7.png)

**Comment by toriato** [comment]
:+1:
