### ISSUE TITLE
Notice: Extension Index - new maintainer

### ISSUE THREAD

**Issue by ClashSAN** [toriato/stable-diffusion-webui-wd14-tagger#107]
Hello, @toriato we'd like to replace your indexed extension with a fork.
If you're happy with this, or if you want to keep the extension listed, let us know!
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/120

**Comment by toriato** [comment]
I have lost interest in development, so please feel free to change it anytime. Thank you for letting me know.
