### ISSUE TITLE
PSA: I'm no longer maintaining this, please use the forked repository

### ISSUE THREAD

**Issue by toriato** [toriato/stable-diffusion-webui-wd14-tagger#108]
I have lost interest in all development activities, including Stable Diffusion. It was only for a short while, but I felt like a developer thanks to the GitHub community which brought me joy. Thank you for using my humble (mostly created by copy and paste!) extensions. Please use the fork from @picobyte going forward.

https://github.com/picobyte/stable-diffusion-webui-wd14-tagger
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/120

To those who sent PRs and issues:
I apologize for not responding for a long time. It might sound like an excuse, but due to mental health issues such as depression and social phobia, I have had a hard time even getting through daily life and found it difficult to check and address these issues. I was also scared to respond due to my limited English skills, but thankfully I am now getting help from ChatGPT.

Big thanks to the Stable Diffusion and stable-diffusion-webui community, catch ya later if I get the chance!!!

**Comment by picobyte** [comment]
Thank you for your work Toriato. I too lose interest sometimes, but hopefully I can keep this one up for a while or I'll try to leave it in good condition. Don't feel too obligued, this is just a community effort, and your contribution already is appreciated, shown by all the stars on your repository. And if ever you have anything to add or comment, you're free to do so.
