### ISSUE TITLE
Batch tagged files including image file extension+.txt

### ISSUE THREAD

**Issue by Evil-Dragon** [toriato/stable-diffusion-webui-wd14-tagger#12]
Typically files created for use with Textual Inversion or Hypernetwork training only include the original filename + txt extension, as an  example:
screenshot_1043.txt to match with screenshot_1043.jpg

However this tagged is creating screenshot_1043.jpg.txt which will be ignored in training sessions.

Just saves people having to use mass renaming software in the long run to make the files work with training.

Everything else works great, thank you :)

**Comment by toriato** [comment]
Added an option to specify the format of the filename with [this commit.](https://github.com/toriato/stable-diffusion-webui-wd14-tagger/commit/b274bc36cccc623c8fde435043df1d39e2c57d03)
Thanks for idea!
