### ISSUE TITLE
Lazy loading?

### ISSUE THREAD

**Issue by toriato** [toriato/stable-diffusion-webui-wd14-tagger#15]
It takes a long time and wastes a lot of resources if you bring in all the models at the start.

**Comment by Evil-Dragon** [comment]
It is a bit lazy and probably eats valuable VRAM when loading the model, I don't mind if it loads the model when you press Interrogate and i have to wait 10 seconds, after that it should be fast.

**Comment by Evil-Dragon** [comment]
Can be closed now since it now only loads when you run the tagger?
