### ISSUE TITLE
Hello, how do I set the default options

### ISSUE THREAD

**Issue by LunarHeron** [toriato/stable-diffusion-webui-wd14-tagger#16]
![QQ截图20221124232405](https://user-images.githubusercontent.com/104299649/203820759-3ef4881c-a03e-4c63-96ff-0662d0c83708.png)
How do I set the default wd14

**Comment by toriato** [comment]
I added a preset to the script, now you can save it to the `default.json` or create a new file to save or load the settings.
To create a new preset, you need to create a new `.json` file in the presets directory in the extension path.
