### ISSUE TITLE
한번 설치해서 써봤는데

### ISSUE THREAD

**Issue by more32** [toriato/stable-diffusion-webui-wd14-tagger#2]
한번 태그 분석하면 메모리를 계속 잡아먹고있음

**Comment by toriato** [comment]
방금 새로 커밋했는데 같은 오류 발생하는지 확인점
https://github.com/toriato/stable-diffusion-webui-wd14-tagger/commit/8e58e4fa0c0b931ac373082e060d3bd3823d7692

**Comment by more32** [comment]
해결됨
