### ISSUE TITLE
Request - save Txt-Files and Edit Tags

### ISSUE THREAD

**Issue by Rartist** [toriato/stable-diffusion-webui-wd14-tagger#23]
Hey there,

I tried your Extension, but it doesn't save the Tags it interrogates.

Please add a Save-Button to save the Tags as [file-name].txt files.

Also it would be great to exclude or include a tag by clicking on it or it's bar. 

Thanks for listening!

**Comment by toriato** [comment]
It is better to use batch process to save tags, but I will add functionality.

**Comment by toriato** [comment]
https://user-images.githubusercontent.com/81617583/206896608-0cf2196a-fa3e-43a0-8b85-b0ec015184bf.mp4

I've implemented the second function, and I'll implement the first one ASAP.

**Comment by toriato** [comment]
Please use the 'Batch from directory' tab for the first feature.
