### ISSUE TITLE
Exclude tags not working as expected

### ISSUE THREAD

**Issue by thojmr** [toriato/stable-diffusion-webui-wd14-tagger#25]
Hey there, thanks for the work on this extension!

I have noticed that the excluded tags are not being excluded, but I can't tell if it's because I have the wrong idea, or not.

If I add `ball` to the excluded list then according to the code below `baseball` should be excluded because the `in` operator is not a `==` comparison. https://github.com/toriato/stable-diffusion-webui-wd14-tagger/blob/a4eb9ecf9a8212a99308a99b793da0e9da1044a5/tagger/interrogator.py#L68

However I still see results containing `ball` like `baseball`, `ball room` in the resulting tag list.  Am I doing something incorrectly?

Also is the exclude list being trimmed of spaces? like `.strip()`

**Comment by toriato** [comment]
https://github.com/toriato/stable-diffusion-webui-wd14-tagger/blob/a4eb9ecf9a8212a99308a99b793da0e9da1044a5/scripts/tagger.py#L282-L291
https://github.com/toriato/stable-diffusion-webui-wd14-tagger/blob/a4eb9ecf9a8212a99308a99b793da0e9da1044a5/tagger/utils.py#L4-L5

`exclude_tags` is a `List`!

I think you misunderstood the variable type. However, it is a good idea to exclude a tag that matches only certain strings!

I will add a function to exclude tags through regular expressions. 

If I misunderstood the issue, please let me know again, I'm using a translator, so please understand.

**Comment by thojmr** [comment]
I figured out the source of my issue.  The excluded tags must have underscores instead of spaces.  Since I checked `Use spaces instead of underscore` I assumed that the exclude tag list would work with spaces too...
