### ISSUE TITLE
Fix for truncated images

### ISSUE THREAD

**Issue by thojmr** [toriato/stable-diffusion-webui-wd14-tagger#28]
Hey again, I would suggest adding the following to avoid the below error.  It's not ideal to be processing 50k images but a single one in the bunch fails the script.

```py
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

Prevents the following error, that stops the run:
```
    image.convert('RGB')
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 901, in convert
    self.load()
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py", line 251, in load
    raise OSError(
OSError: image file is truncated (5 bytes not processed)
```

**Comment by toriato** [comment]
Thank you for letting me know the issue and the solution! can you check if it's resolved?

**Comment by thojmr** [comment]
I would if I had not converted all the truncated images last night XD
I've been using that flag in other projects on both windows and Ubuntu for a while now.  It should be fine.
