### ISSUE TITLE
Allow model unloading from VRAM

### ISSUE THREAD

**Issue by vibrantrida** [toriato/stable-diffusion-webui-wd14-tagger#31]
My gpu don't have enough VRAM, it would be nice to have a way to unload the tagger model from VRAM at will incase I run into "out of memory" error during inference

**Comment by toriato** [comment]
There is a bug in Keras where it is not possible to release a model from memory. 
Downgrading to keras==2.1.6 may fix the issue, but it may also cause compatibility problems with other packages.
Using subprocess to create a new process may also solve the issue, but it can be too complex.
For now, it seems that the best option is to keep the model in memory, as most users use the Waifu Diffusion model with onnx.
