### ISSUE TITLE
Issue installing & applying extension.

### ISSUE THREAD

**Issue by spedman334** [toriato/stable-diffusion-webui-wd14-tagger#32]
When installing extension:
```
Error running install.py for extension /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger.
Command: "/usr/bin/python3" "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/install.py", line 1, in <module>
    import launch
ModuleNotFoundError: No module named 'launch'
```

And then when applying and restarting:
```
Error executing callback ui_tabs_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 95, in ui_tabs_callback
    res += c.callback() or []
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py", line 172, in on_ui_tabs
    interrogator_names = refresh_interrogators()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py", line 44, in refresh_interrogators
    shared.cmd_opts.deepdanbooru_projects_path,
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'
```

The UI for the tagger does not appear after applying and restarting, installed the extension using "Install from URL." I am using https://github.com/TheLastBen/fast-stable-diffusion.

**Comment by PletPeter** [comment]
way to use anyway: open the folder in your extensions map with git gui/ command prompt. then type `git checkout 964437a`. Then restart your webui

This will use the build that is known to work.

**Comment by coronet1127** [comment]
add
  # load deepdanbooru project

    deepdanbooru_projects_path = 
    "C:/Users/coron/OneDrive/デスクトップ/sd-web ui/stable-diffusion-webui/models/torch_deepdanbooru"
    shared.cmd_opts.deepdanbooru_projects_path = deepdanbooru_projects_path

    os.makedirs(
        shared.cmd_opts.deepdanbooru_projects_path,
        exist_ok=True

**Comment by toriato** [comment]
It seems that this may be related to Issue #36. Has the problem been resolved?

**Comment by toriato** [comment]
If the error persists, please leave a response on Issue #36. If it seems unrelated, please reopen this issue.

**Comment by ucdxu** [comment]
> add
> 
> # load deepdanbooru project
> ```
> deepdanbooru_projects_path = 
> "C:/Users/coron/OneDrive/デスクトップ/sd-web ui/stable-diffusion-webui/models/torch_deepdanbooru"
> shared.cmd_opts.deepdanbooru_projects_path = deepdanbooru_projects_path
> 
> os.makedirs(
>     shared.cmd_opts.deepdanbooru_projects_path,
>     exist_ok=True
> ```

It does not work for me.
