### ISSUE TITLE
Please add Waifu Diffusion tagger v2

### ISSUE THREAD

**Issue by RandyRandom** [toriato/stable-diffusion-webui-wd14-tagger#39]
Smiling Wolf released 3 days ago new v2 models for tagging. Would be nice if the extension added support for those.

https://huggingface.co/SmilingWolf/wd-v1-4-swinv2-tagger-v2
https://huggingface.co/SmilingWolf/wd-v1-4-convnext-tagger-v2
https://huggingface.co/SmilingWolf/wd-v1-4-vit-tagger-v2

**Comment by MrRace** [comment]
where should I put the models? I manually download the models
