### ISSUE TITLE
Requesting Subfolders

### ISSUE THREAD

**Issue by RealBeyondMaster** [toriato/stable-diffusion-webui-wd14-tagger#44]
Hello there

Would it be possible to enhance the functionality to include subfolders? That would be really nice and save some manual work.
Thank you!

**Comment by toriato** [comment]
Did you mean recursion? it may have already been implemented.
Try `/path/to/images/**/*` in the input path.

**Comment by RealBeyondMaster** [comment]
Oh my god, that works, was looking for exactly that. Thanks a bunch!!!
