### ISSUE TITLE
Append tags does not add trailing comma to existing tags

### ISSUE THREAD

**Issue by space-nuko** [toriato/stable-diffusion-webui-wd14-tagger#49]
For example if the existing caption text file has `solo, 1girl` and the tagger adds `blue eyes`, the tags become `solo, 1girl blue eyes`. I expect `solo, 1girl, blue eyes`

Also the tagger doesn't fix trailing newlines in the existing caption

**Comment by toriato** [comment]
Has the issue been resolved? Please open it again if necessary.

**Comment by picobyte** [comment]
it is resolved with #93
