### ISSUE TITLE
exclude tag does't work

### ISSUE THREAD

**Issue by xjlin** [toriato/stable-diffusion-webui-wd14-tagger#55]
Hi,
I have add some tag in exclude tag,like 
`virtual youtuber,long hair,black skirt,navel,jewelry,shirt,choker,bracelet,red shirt,belt,miniskirt,hair bow,earrings,hair bow`
but in txt file, I still can find these tags.
`default, 1girl, solo, purple hair, star hair ornament, long hair, crop top, salute, bow, star (symbol), purple eyes, hair bow, red bow, hair ornament, black background, smile, looking at viewer, heart, virtual youtuber, upper body, sketch, midriff, black choker, cropped shirt, simple background, red shirt, star earrings, heart earrings, short sleeves, wristband, bangs, black shirt, collarbone`

**Comment by ThanapatSornsrivichai** [comment]
Confirmed it doesn't work on Automatic1111

**Comment by ThanapatSornsrivichai** [comment]
Use underscore instead of spacebar.
cropped_shirt, simple_background instead of cropped shirt, simple background

**Comment by xjlin** [comment]
Thanks, it works.
