### ISSUE TITLE
Can't load Tagger

### ISSUE THREAD

**Issue by JohnWJarrett** [toriato/stable-diffusion-webui-wd14-tagger#9]
Installed today, used once, worked great, updated and then this:

> Error loading script: tagger.py
> Traceback (most recent call last):
>   File "J:\SD\ASD\modules\scripts.py", line 184, in load_scripts
>     module = script_loading.load_module(scriptfile.path)
>   File "J:\SD\ASD\modules\script_loading.py", line 13, in load_module
>     exec(compiled, module.__dict__)
>   File "J:\SD\ASD\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py", line 13, in <module>
>     from tagger import supported_extensions, interrogate_tags, postprocess_tags
> ImportError: cannot import name 'supported_extensions' from 'tagger' (J:\SD\ASD\extensions\stable-diffusion-webui-wd14-tagger\tagger.py)

**Comment by Baku-Rue** [comment]
Having the same issue on mine as well. In order to get it to work again I had to checkout an older version using the command below:

`git checkout a7ab637113385bc9f94d2404b18ddb960cc14752`

**Comment by JohnWJarrett** [comment]
Thanks!

**Comment by BetaDoggo** [comment]
Removing the "supported_extensions" import from line 13 in ./scripts/tagger.py and commenting out every line after it referencing supported_extensions fixes the issue on the current commit. Obviously it breaks the file extension check though.

**Comment by toriato** [comment]
Quick fix, I made a mistake, sorry!
I made a typo in the commit message too, double sorry!

**Comment by JohnWJarrett** [comment]
All good, thanks for the fix!
